spring:
  application:
    name: space-reservation-application

  datasource:
    url: jdbc:mysql://localhost:3306/space_reservation_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

