spring:
  application:
    name: space-reservation-application

  datasource:
    url: jdbc:mysql://localhost:3306/space_reservation_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: GMT+04:00

server:
  port: 8080

org:
  td024:
    auth:
      jwt-secret: ${JWT_SECRET}
      session-timeout: 3600
      refresh-timeout: 7200
